version: "3.9"
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg_discord_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ds_bot:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    container_name: ds_bot
    env_file: .env
    depends_on:
      - postgres

volumes:
  pg_discord_data:
