"""empty message

Revision ID: 519d24a4bbc8
Revises: bd3ad5c737f0
Create Date: 2023-03-13 14:35:25.376860

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '519d24a4bbc8'
down_revision = 'bd3ad5c737f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discord_config', sa.Column('log_message_channel', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discord_config', 'log_message_channel')
    # ### end Alembic commands ###
