"""initial

Revision ID: 5a4e8cea0797
Revises: 
Create Date: 2023-03-05 20:34:47.467321

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5a4e8cea0797'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('find_friends_cooldown', sa.BigInteger(), nullable=True),
    sa.Column('find_friends_channel', sa.BigInteger(), nullable=True),
    sa.Column('magic_avatar_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_config')
    # ### end Alembic commands ###
