"""empty message

Revision ID: 73bc3b821d41
Revises: f985b88e00e0
Create Date: 2023-03-13 09:20:12.129698

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '73bc3b821d41'
down_revision = 'f985b88e00e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'message_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('text', sa.String(), nullable=True),
        sa.Column('image_url', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_templates')
    # ### end Alembic commands ###
