"""empty message

Revision ID: bd3ad5c737f0
Revises: 73bc3b821d41
Create Date: 2023-03-13 14:32:19.692360

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bd3ad5c737f0'
down_revision = '73bc3b821d41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
