"""empty message

Revision ID: f985b88e00e0
Revises: 5a4e8cea0797
Create Date: 2023-03-05 20:42:56.535699

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f985b88e00e0'
down_revision = '5a4e8cea0797'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discord_config', 'magic_avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discord_config', 'magic_avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
