name: Deploy bot
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: "Build and Run"
    runs-on: ubuntu-latest
    steps:
      - name: Connect and Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
        scripts: |
          cd code/discord_bot
          git pull
          sudo make build
